/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.texstudio.memesprojectredisc;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class MemesprojectRediscModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public MemesprojectRediscModElements() {
		sounds.put(new ResourceLocation("memesproject_redisc", "egg_breaked"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "egg_breaked")));
		sounds.put(new ResourceLocation("memesproject_redisc", "internet_overdose"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "internet_overdose")));
		sounds.put(new ResourceLocation("memesproject_redisc", "only_my_railgun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "only_my_railgun")));
		sounds.put(new ResourceLocation("memesproject_redisc", "be_crazy_for_me"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "be_crazy_for_me")));
		sounds.put(new ResourceLocation("memesproject_redisc", "bad_apple_original"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "bad_apple_original")));
		sounds.put(new ResourceLocation("memesproject_redisc", "bad_apple"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "bad_apple")));
		sounds.put(new ResourceLocation("memesproject_redisc", "never_gonna_give_you_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "never_gonna_give_you_up")));
		sounds.put(new ResourceLocation("memesproject_redisc", "freesia"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "freesia")));
		sounds.put(new ResourceLocation("memesproject_redisc", "go_yang_ubur_ubur_remixed"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "go_yang_ubur_ubur_remixed")));
		sounds.put(new ResourceLocation("memesproject_redisc", "night_voyager"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "night_voyager")));
		sounds.put(new ResourceLocation("memesproject_redisc", "shooting_stars"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "shooting_stars")));
		sounds.put(new ResourceLocation("memesproject_redisc", "dreamer"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "dreamer")));
		sounds.put(new ResourceLocation("memesproject_redisc", "underworld"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "underworld")));
		sounds.put(new ResourceLocation("memesproject_redisc", "underworld_eiko"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "underworld_eiko")));
		sounds.put(new ResourceLocation("memesproject_redisc", "shooting_star"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "shooting_star")));
		sounds.put(new ResourceLocation("memesproject_redisc", "make_it_real"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "make_it_real")));
		sounds.put(new ResourceLocation("memesproject_redisc", "choco_pate"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "choco_pate")));
		sounds.put(new ResourceLocation("memesproject_redisc", "im_still_alive_today"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "im_still_alive_today")));
		sounds.put(new ResourceLocation("memesproject_redisc", "find_the_way"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "find_the_way")));
		sounds.put(new ResourceLocation("memesproject_redisc", "im_still_alive_today_eiko_nanami"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "im_still_alive_today_eiko_nanami")));
		sounds.put(new ResourceLocation("memesproject_redisc", "im_still_alive_today_nanami"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "im_still_alive_today_nanami")));
		sounds.put(new ResourceLocation("memesproject_redisc", "im_still_alive_today_acoustic"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "im_still_alive_today_acoustic")));
		sounds.put(new ResourceLocation("memesproject_redisc", "roppongi_udon_shop_provisional"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesproject_redisc", "roppongi_udon_shop_provisional")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("memesproject_redisc").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == MemesprojectRediscModElements.ModElement.class)
						elements.add((MemesprojectRediscModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(MemesprojectRediscModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		MemesprojectRediscMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final MemesprojectRediscModElements elements;
		protected final int sortid;

		public ModElement(MemesprojectRediscModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
